sources:
  - name: Notion
    handler:
      jsonSchema:
        source: https://api.notion.com/v1
        operations:
          - type: Query
            field: page
            path: /pages/{args.id}
            method: GET
            responseSample: ./schemas/Page.response.json
            responseTypeName: Page